### ISSUE TITLE
"Hidden" plugin is visible via search

### ISSUE THREAD

**Issue by chrisparker2000** [mkaply/cck2wizard#1]
Steps to reproduce:
1. Create CCK2 configuration where a plugin is specified and it is set to be hidden.
2. Deploy configuration
3. Launch Firefox
4. Go to the addons page and the extensions subpage
5. Search for part of the addon that you hid
6. Click on my addons radio button
7. Hidden extension now visible and can be disabled.

When I reproduced this I was installing a plugin that was NOT the cck2 plugin, so I was kinda abusing the feature I think.  I also didn't reproduce it in the latest version (meaning I didn't try), but this functionality was consistent between firefox versions 38-43.

**Comment by mkaply** [comment]
Thanks for reporting this. I've switched the mechanism I use to hide it, so it should be more reliable.
