### ISSUE TITLE
CCK2 trows error in FF63 (XPCOMUtils.generateQI is not a function)

### ISSUE THREAD

**Issue by NickETH** [mkaply/cck2wizard#101]
TypeError: XPCOMUtils.generateQI is not a function[Learn More] Preferences.jsm:593:19
Seems to me, that this function was removed from XPCOM.
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1484466

Can you fix this, please?

Thanks, Nick

**Comment by nakosenk** [comment]
You can get up and running by changing XPCOMUtils to ChromeUtils without having to make any other changes to the file.

**Comment by NickETH** [comment]
Hi,
thanks a lot. That did the trick.
Had to alter the following lines in the module files:
CCK2.jsm: Line 1402.
Preferences.jsm: Line 593.
CCK2FileBlock.jsm: Line  33.

Thanks, Nick

**Comment by mkaply** [comment]
I've fixed this with the latest code.
