### ISSUE TITLE
CA Certificate load error with latest CCK2 and ESR 68.0

### ISSUE THREAD

**Issue by jcpearson** [mkaply/cck2wizard#102]
OK, I know I should really be using policies, but I thought I would see if our existing ESR 60 set up would work - which it almost does, but it fails to load our CA cert files

I'm using the latest CCK2 modules from git and the latest ESR 68.0 release candidate - and get the error:

CCK2: Unable to install resource://mpc/certs/InternalChain.crt - [Exception... "Not enough arguments [nsIIOService.newChannelFromURI]"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: resource://cck2/CCK2.jsm :: download :: line 1360"  data: no]

errorCritical@resource://cck2/CCK2.jsm:1314:13
observe@resource://cck2/CCK2.jsm:943:21
CCK2.jsm:1316
    errorCritical resource://cck2/CCK2.jsm:1316
    observe resource://cck2/CCK2.jsm:943

**Comment by jcpearson** [comment]
It looks like newChannelFromURI() now needs 6 arguments, not 1 (???) - after a bit of hackery and guesswork (searching the mozilla source), I've got it to work ... but I suspect your real fix will be much better than mine :-)

**Comment by mkaply** [comment]
Just did an update that fixes this. Thanks!
