### ISSUE TITLE
win is null in CAPSClipboardFramescript

### ISSUE THREAD

**Issue by cjcenizal** [mkaply/cck2wizard#103]
Hi there, I'm a maintainer of [Kibana](https://github.com/elastic/kibana) and we've had reports from some of our users who also use CCK2 of crashes due to `win` being `null` at https://github.com/mkaply/cck2wizard/blob/master/cck2/modules/CAPSClipboardFramescript.js#L72. I'm not familiar with CCK2's source code so I'm not sure how this could evaluate to null or how Kibana could be causing this, but I thought I would suggest a null check here and on similar lines to protect CCK's users from this problem. Thanks!

**Comment by mkaply** [comment]
That's really odd. That genuinely should never happen, but I'll add a null check.
