### ISSUE TITLE
Certificates are not being configured by CCK2 2.1.2

### ISSUE THREAD

**Issue by nfcupackager** [mkaply/cck2wizard#19]
When a url is provided for a website in autoconfig, the certificates are not being automatically added to the certificate store on the launch of firefox.

**Comment by mkaply** [comment]
I tested this and it worked for me. Same comment as the other cert bug, though. Certs are only added when the CCK2 is first installed or the version is bumped, so if you make these changes to an existing CCK2, they won't be picked up.
