### ISSUE TITLE
The self-signed certificate excetion option in version 2.1.2 is not being configured

### ISSUE THREAD

**Issue by nfcupackager** [mkaply/cck2wizard#20]
When CCK2 is used to specify a url as an exception to the self-signed rule FireFox still prompts said website for a manual exception.

**Comment by mkaply** [comment]
I just ran a test of this and it is working for me. I added a domain to the list and after starting the CCK2 and going to that domain, I did not receive a certificate error.

Note that cert exceptions are only added when the CCK2 is first installed or the version is bumped, so if you make these changes to an existing CCK2, they won't be picked up.
