### ISSUE TITLE
Override signatures cannot be removed once added via CCK2

### ISSUE THREAD

**Issue by nfcupackager** [mkaply/cck2wizard#21]
The signatures can only be removed via direct editing of the json file.

**Comment by mkaply** [comment]
The UI is kind of on obvious, but you can press the delete button and delete them...

**Comment by nfcupackager** [comment]
thank you for the quick reply mike, there is no delete button in the UI or the right click context menu.
screenshot attached.

![capture](https://cloud.githubusercontent.com/assets/14941094/16197923/e197ff5a-36d1-11e6-88e0-17bf5179be4c.PNG)

**Comment by mkaply** [comment]
Delete key on the keyboard. Sorry. I really should add some more UI here.

**Comment by nfcupackager** [comment]
thank you, I don't know why I didn't try that, so I guess this would be more of a feature request for more ui rather than an issue
