### ISSUE TITLE
Unreachable code in certExists in cck2.jsm

### ISSUE THREAD

**Issue by chrisparker2000** [mkaply/cck2wizard#38]
More of an FYI than anything else.  Firefox 50 complains about it. Obviously not a huge issue, but I thought you might want to be aware of it.

`09:58:21.332 unreachable code after return statement 1 CCK2.jsm:947:2`

`function certExists(cert) {
  return false;
  var actualCert = certdb.constructX509FromBase64(fixupCert(cert));
  try {`

**Comment by mkaply** [comment]
Thanks. I'll remove that in the next release. I used to check for certs before adding them but there's no need to.
