### ISSUE TITLE
In identifier text box, colon should be excluded

### ISSUE THREAD

**Issue by pfparesseux000** [mkaply/cck2wizard#40]
Tested with CCK2 Wizard 2.2.2 on Firefox 49.0.2 on Windows XP French.

In the identifier text box, colon (and semicolon...) should be excluded too.
Because after adding certificates, and opening for the first time Firefox, an error is displayed, and the certificates are not added in Firefox.

Steps to Reproduce:
When creating new CCK2 configurations
Name : cck2 2016-12-12 14:30:00
Identifier : cck2_2016-12-12_14:30:00
In Certificates, add certificates.
In Finish, click on Use AutoConfig button.
Unzip autoconfig.zip and copy cck2\, defaults\, and cck2.cfg in C:\Program Files\Mozilla Firefox\.
Make sure there is no %AppData%\Mozilla\ directory.
Open Firefox.

Actual Results:
An error is displayed: Unable to install resource://cck2_2016-12-12_1430:00/certs...
And the certificates are not added in Firefox.

Cause of the problem:
In the identifier text box, colon (and semicolon...) mustn't be used two times.

Alternative way:
In the identifier text box, I replace colons with dashes.
Identifier : cck2_2016-12-12_14-30-00

**Comment by mkaply** [comment]
So the actual bug here is that I am only replacing the first instances of things.

  var packageName = config.id.replace("@", "").replace("#", "").replace(";", "")
                             .replace(":", "").replace("?", "").replace("/", "");

I'll fix.
