### ISSUE TITLE
Add multiprocessCompatible tag to install manifest

### ISSUE THREAD

**Issue by ralther** [mkaply/cck2wizard#42]
As part of electrolysis compatibility, the multiprocessCompatible tag should be include in the CCK2 wizard manifest as well as the generated CCK extension.
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible

**Comment by mkaply** [comment]
Good call.

**Comment by mkaply** [comment]
Fixed
