### ISSUE TITLE
plugins go into user profile (forever)

### ISSUE THREAD

**Issue by arlt** [mkaply/cck2wizard#5]
Until now we distribute addons in unpacked form into _C:\Program Files (x86)\Mozilla Firefox\browser\extensions_. The addons are only available until the get removed from this folder.

With CCK2 (autoconfig version unpacked to installation folder) they get copied during use of firefox to the users profile folder (subfolder _extensions_).

If i simulate a new distribution of firefox with a removed addon:
- close Firefox
- remove the xpi from _C:\Program Files (x86)\Mozilla Firefox\cck2\resources\addons_
- remove the addons-resource from _C:\Program Files (x86)\Mozilla Firefox\cck2.cfg_
- start Firefox again

... the addon remains in _%appdata%\Roaming\Mozilla\Firefox\Profiles\jzsq8jqn.default\extensions_ and is useable.

I am not sure if i understand Firefox good enough – but maybe an option to unpack the xpi’s to browser\extensions would be a good solution?

**Comment by mkaply** [comment]
If you want to put addons into browser/extensions, you can continue to do that independent of the CCK2.

Addons that are bundled with the CCK2 are installed as if they were installed by the user, so they go into the profile directory.

That's the way it was intended to be.

I've considered adding the ability to explicit uninstall an extension from the CCK2, but that's not something that will happen anytime soon.

**Comment by arlt** [comment]
Yes, that works. Thanks.

I really prefer the provisioning via browser\extensions - that is a clean way: No addon can be forgotten in the users profile. I combined this with cck2. It would be great if cck2 could handle the annoying unpacking and renaming of the addon folders but anyway.

If you implement addons-uninstall from the users profile: Consider to uninstall all addons.
Explanation: phase1: addons a,b,c; phase2: addons a,b; phase3: addons a,b.
If you uninstall only specific addons (e.g. "c" in phase2), a user who uses his Firefox in Phase 1 and Phase 3 will have the addon "c" at the end.

Thanks for this amazing tool!
