### ISSUE TITLE
Question about a new pref : security.insecure_field_warning.contextual.enabled

### ISSUE THREAD

**Issue by mathieuga** [mkaply/cck2wizard#56]
Hi,
Thank for this great tool!

I have a question about a new pref : security.insecure_field_warning.contextual.enabled
I want to customise this perf  but it is not work because this pref is duplicate.
Is it a "normal" feature ? 

![image](https://cloud.githubusercontent.com/assets/8363615/24052114/99a31cec-0b34-11e7-9958-fa700002d932.png)

Best regard
Mathieu

**Comment by mkaply** [comment]
That's quite strange. That shouldn't happen. Is there maybe a space at the end of one of preferences?

Can you look in the cck2.cfg file directly?

**Comment by mathieuga** [comment]
Yes it is a space ... 
Thanks for the tip.
