### ISSUE TITLE
"Don't show snippets on about:home" option broken in Firefox 52

### ISSUE THREAD

**Issue by steven676** [mkaply/cck2wizard#60]
Firefox 52.1.0esr (64-bit) on Windows 7 x64 displays snippets on about:home despite having a CCK2 autoconfig with just the "Don't show snippets on about:home" option set installed.  The identical autoconfig works fine with Firefox 45.9.0esr (32-bit) on the same system.

I've attached the [autoconfig.zip](https://github.com/mkaply/cck2wizard/files/948647/autoconfig.zip) I created (with CCK2 Wizard 2.2.3.2) for this test case.

**Comment by mkaply** [comment]
It's working for me on 64 and 32 with your autoconfig.

Is it still happening? I wonder if it was a particular snippet? Can you check the console and see if there are any errors?

Also can you check about:support and see if you are multiprocess or not.

**Comment by steven676** [comment]
Just tried again with an uninstall/reinstall of Firefox 52.1.0esr; it
still happens, but only with the existing profile on this test machine
(which has been around since Firefox 31, probably).  A new profile
doesn't show the problem (even after I install CCK2 Wizard version
2.2.3.2, the only addon installed in the old profile).

I've gotten this with both built-in and downloaded snippets, so I don't
think it's to do with a specific snippet.  I don't think it has to do
with upgrading profiles from previous versions either -- I tested
another profile that had been used with Firefox 45 on another machine (a
Windows 10 machine, for whatever that's worth) and didn't see this
problem either.

The web console is completely blank even after reloading the page.  The
browser console shows the same contents when about:home is loaded in
either profile:

    Use of nsIDOMWindowInternal is deprecated. Use nsIDOMWindow instead.  bootstrap.js:216:20
    Content Security Policy: Couldn’t process unknown directive ‘worker-src’  (unknown)
    Content Security Policy: Directive ‘frame-src’ has been deprecated.  Please use directive ‘child-src’ instead.  (unknown)
    SHIELD active  selfrepair.aab6b9ecf3d4537052d5.js:9:8035

(The first message only appears in the brand-new profile when CCK2
Wizard is installed, so I doubt it's relevant.)

about:support shows multiprocess is "enabled by default" in both cases.

It'd be nice to know why this is happening, but I guess I wouldn't be
opposed to ignoring this as a byproduct of some profile weirdness at
this point.  (It's not as if the affected profile is even lightly
customized, though ...)

**Comment by mkaply** [comment]
about:home is going away in Firefox 60, so this is a won't fix.
