### ISSUE TITLE
Firefox 57/Web Extension Support

### ISSUE THREAD

**Issue by mattpwhite** [mkaply/cck2wizard#62]
Hi,
Is there any plan to convert the CCK2 wizard to a web extension?  More generally, are there plans to continue maintaining the CCK2 functionality going forward?  It seems like there hasn't been much activity for the past several months, so the status of the project seems unclear.  The GUI is nice to bootstrap a config, but if it went away, but the CCK2 modules were maintained and we just had to build the config by hand, that would still be useful.

Thanks for your work on CCK2 in general over the years, without it it's unlikely that we could have justified the effort to support Firefox on our fleet of machines.

**Comment by mkaply** [comment]
The wizard itself can't really be a WebExtension, but can continue to run on the Firefox 52 ESR.

I plan to do my best to maintain the CCK2 autoconfig piece for the foreseeable future.

**Comment by mattpwhite** [comment]
Thanks for your response, the autoconfig piece is what is important to us.
