### ISSUE TITLE
FF 57.0 says "CCK2 Wizard could not be installed because it is not compatible with Firefox 57.0"

### ISSUE THREAD

**Issue by bripakes** [mkaply/cck2wizard#65]
FF 57.0 on macOS 10.12.6 presents warning when opening cck2_wizard-2.2.3.4-fx.xpi:

"CCK2 Wizard could not be installed because it is not compatible with Firefox 57.0"

Add-ons Manager states CCK2 Wizard 2.2.3.4 is Legacy and disabled.

Is there a way I can get CCK2 to work with FF 57.0 on a Mac?

Brian

**Comment by mkaply** [comment]
See:

https://mike.kaply.com/2017/11/15/firefox-quantum-and-cck2/

To use the CCK2 Wizard, you'll have to use the Firefox 52 ESR.
