### ISSUE TITLE
2.2.3.4 xpi not installable

### ISSUE THREAD

**Issue by NuLogicSystems** [mkaply/cck2wizard#68]
xpi installer pop up says not compatible with Firefox 57

**Comment by mkaply** [comment]
See:

https://mike.kaply.com/2017/11/15/firefox-quantum-and-cck2/

**Comment by NuLogicSystems** [comment]
I meant the xpi here: https://github.com/mkaply/cck2wizard/releases
I figured since it mentions 57 then it was compatible, I guess I was wrong then.
Sorry to have bothered you.

**Comment by mkaply** [comment]
that's a really great point. I'll make it clear that I mean "creating configs for 57" not running on it. 

Thanks for the feedback!
