### ISSUE TITLE
Firefox 58 beta not working with cck2

### ISSUE THREAD

**Issue by care2bfree** [mkaply/cck2wizard#71]
Just as a heads up, I have Firefox 57 working well with cck2 but with Firefox 58 I'm getting the same error that 57 exhibited before applying your recent fixes for that version.

**Comment by mkaply** [comment]
I do have a fix, just need to get a new CCK2 built.

**Comment by mkaply** [comment]
I just released a new CCK2 for this

https://github.com/mkaply/cck2wizard/releases/tag/2.2.3.5
