### ISSUE TITLE
Can't import automatically a root certificate (while others are ok)

### ISSUE THREAD

**Issue by FranckSartori** [mkaply/cck2wizard#72]
Hi from France.
I have an issue with using CCK2 to generate an autoconfig configuration that should import a specific root certificate.
Once Firefox is launched, I get the error message in attachment.
Note that I can import other certificates in the same autoconfig configuration and these ones are successfully imported.
I can even import the faulty certificate manually using Firefox Preferences and it is then ok.
I don't see why this particular one does not want to install.
I can provide the default certificate on request by the developer team.
Best regards.

<img width="586" alt="screen shot 2018-01-04 at 10 33 06" src="https://user-images.githubusercontent.com/4460512/34561477-84d79e8a-f14a-11e7-8be9-e2fab763c9eb.png">

**Comment by mkaply** [comment]
Can you send me the complete ZIP file and I'll take a look? consulting@kaply.com

**Comment by FranckSartori** [comment]
Hi Michael.

Thanks for your message.

I asked the packaging team to deliver me again the same certificate both in DER and Base 64 formats.

And these 2 provided ones imports successfully using either the manual method and CCK2.

Whereas as I said, the first one provided could be imported successfully manually but not using CCK2.

That is very weird.

I don't have anymore the first one to see how it was encoded and to be able to compare its content with the 2 new ones.

So the topic is considered as closed.

Actually the customer still deploys Firefox 56. I read that the CCK2 extension can't be used with Firefox 57+ right now. I follow your blog to see what is going on.

Thank you for your support !

Franck.
