### ISSUE TITLE
CCK2 on Quantum ignores NoScript whitelist

### ISSUE THREAD

**Issue by Zeremon** [mkaply/cck2wizard#77]
Since Firefox 57 Quantum the NoScript whitelist defined in the auto config cck2.cfg has no effect when Firefox is launched with e new profile (i.e. no preexisting user settings). We define presets of the NoScript whitelist in the CCK (version 2.2.3.5) configuration (autoconfig cck2.cfg) )using the string value "capability.policy.maonoscript.sites". This method formerly let CCK write the settings in the user's prefs.js and NScript then applied the white list flawlessly . Unfortunately the new webextensions version of NoScript writes its whitelist into the data base file **storage-sync.sqlite**. It seems that the CCK does not take this change into account. Even though I see this setting in about:config it ist not written neither into prefs.js nor the storage-sync.sqlite.

I want to add, that regarding my request for help on the NoScript's forums.informaction.com their advice was "This sounds like a CCK question, not a NoScript question. I suggest you ask the CCK folks."

For us this bug is troublesome as the user is already confronted with a scrambled enterprise welcome page the first time she/he opens Firefox until she/he trusts them in NoScript.

Thanks a lot for any advice or solution.

Klaus

**Comment by Zeremon** [comment]
Sorry, the comment was sent prematurely. I want to add, that regarding my request for help on the NoScript's forums.informaction.com was answered with the advice "This sounds like a CCK question, not a NoScript question. I suggest you ask the CCK folks."

For us this bug is troublesome as the user is already confronted with a scrambled enterprise welcome page the first time she/he opens Firefox until she/he trusts them in NoScript.

Thanks a lot for any advice or solution.

Klaus

**Comment by Zeremon** [comment]
A possible workaround could be to copy a pre-configured storage-sync.sqlite into every newly created profile.
I could imagine that there are other use cases in enterprise environments where you would like to deliver one file or another on creation of every new profile. 
Are such copy actions feasible or even already provided with the CCK Wizard?

Thanks for any suggestion!

**Comment by Zeremon11** [comment]
Found a solution: First we feed the whitelist storage-sync.sqlite of a pristine profile with the desired domains. Then we copy storage-sync.sqlite and the subfolder browser-extension-data\{73a6fe31-595d-460b-a920-fcc0f8843232}\storage.js to the C:\Program Files\Mozilla Firefox\defaults\profile folder. Thus every new profile will get these files at first start. If you copy these files manually to existing profiles you get the same effect.

**Comment by mkaply** [comment]
Yeah, there isn't much the CCK2 can do here since it's no longer a preference. Glad you found a workaround.
