### ISSUE TITLE
unable to install cck2 on ff58.0.2 mac

### ISSUE THREAD

**Issue by tkimpton** [mkaply/cck2wizard#78]
unable to install cck2 extension on ff58.0.2 mac

mike.kaply.com

CCK2 Wizard could not be installed because it is not compatible with Firefox 58.0.2.

**Comment by amitpatel99** [comment]
I would be interested in how to do this if you find out too?
Thanks.

**Comment by charliwest** [comment]
You might want to have a read here https://mike.kaply.com/category/mozilla/

**Comment by tkimpton** [comment]
Yeah I did after posting and all good

**Comment by mkaply** [comment]
Thanks @charliwest  That was going to be my reply :)

**Comment by tkimpton** [comment]
looking at this with 58.0.2 the crash reporter is not suppressed ( even through this is specified in the cck) and updon deployment any cck configuration within the app bundle causes the crash reporter to po up. Without this there is no issues. I believe this is not sustainable in Firefox Quantum to ever use cck again unless it is completely re-written to work with Firefox Quantum and above.

**Comment by tkimpton** [comment]
@charliwest you may want to read this

**Comment by mkaply** [comment]
The crash reporter not being suppressed is a Firefox issue. I plan to remove that from the CCK2 for now.

As far as the crashes at startup,. folks have them intermittently and the solution was to remove the users cache folder or not set permissions.

I'm trying to figure out things, but it's getting more and more difficult. My best suggestion would be to use the ESR (as it has always been)

**Comment by tkimpton** [comment]
Or in this case where lastest non esr is required, stop using cck and script the settings
