### ISSUE TITLE
Can't install latest version cck2 in FF 58.0.2

### ISSUE THREAD

**Issue by psyapathy** [mkaply/cck2wizard#82]
Hello!. I Can't install latest version cck2 in FF 58.0.2 =( He says me that "incompatible with FF 58.0.2"

**Comment by TotalMoop** [comment]
The Extension only works up to v56 of FF. 
Use the older FF to install the extension on a spare machine or VM and create the Autoconfig from there.
You should then be able to use the configuration in later versions.

**Comment by mkaply** [comment]
Yes. You have to use Firefox 56 or below to use the CCK2 itself. The code you get works on any version.

See:

https://mike.kaply.com/2017/11/15/firefox-quantum-and-cck2/
