### ISSUE TITLE
CCK 2.2.5 doesn't seem to apply settings to FF 61

### ISSUE THREAD

**Issue by tsherrington** [mkaply/cck2wizard#89]
I've been using CCK for a long time, and I use it two ways:  1)Fresh installs of FF and 2)Updates of FF.

For the updates, I uninstall FF (without removing the profile) and then I install FF, copy the CCK files to the FF program folder and then start FF

These are the changes I'm making:
1)Installing the Canadian English Dictionary (using the URL https://addons.mozilla.org/firefox/downloads/file/687952/canadian_english_dictionary-3.0.5-fx+sm+tb.xpi)
2)Adding a link to my website to the Bookmark Toolbar and Menu.
3)Turning off proxy.
4)Set FF to check if it's the default.

This has always applied the CCK2 settings without a problem, but now, it only turns off the proxy.  It doesn't seem to apply any other settings.  It does add the CCK line to the Help/About Firefox page.

Any idea what I'm doing wrong?

**Comment by mkaply** [comment]
Can you check the error console to see if there is an error (Ctrl+Shift+J)

**Comment by tsherrington** [comment]
Hi Michael, here's what I get.

Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:1
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:7
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2
NS_ERROR_XPC_BAD_IID: Component returned failure code: 0x80570018 (NS_ERROR_XPC_BAD_IID) [nsIJSCID.getService] CCK2.jsm:1034
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul

**Comment by mkaply** [comment]
Sorry for the delay. I found this and I'm putting in a fix.

**Comment by mkaply** [comment]
I hope to have  a new version out today. Tracking down one more thing.

**Comment by tsherrington** [comment]
Fantastic!  Thanks Mike.  I've been trying to get the new policies.json system to work, but it doesn't appear to yet.

**Comment by tsherrington** [comment]
Hi Mike, did you get a chance to complete the fix?

**Comment by mkaply** [comment]
Sorry, have a fix, but I was trying to get a fix to bookmarks as well.

The fix is here:

https://github.com/mkaply/cck2wizard/commit/4f48681e7467182c9ac1e5d06dce099b2c07b384

You can make the change to your local copy of CCK2.jsm if you want to try it out.

**Comment by mkaply** [comment]
New version is up

https://mike.kaply.com/updates/cck2wizard/cck2_wizard-2.6.5-fx.xpi
