### ISSUE TITLE
2.2.7-Extensions fail to load with firefox-esr v52.9

### ISSUE THREAD

**Issue by bHKSG3kp** [mkaply/cck2wizard#94]
I suspect this diff, the new API is probably not available in the ESR version of firefox?
```
-  AddonManager.getInstallForURL(config.addons[i], "application/x-xpinstall").then(addonInstall => {
+  try {
+  AddonManager.getInstallForURL(config.addons[i], function(addonInstall) {
```

Also, any preference (or upstream doc.) on the URL format for extensions from addons.mozilla.org ?

For example:
(1.)  https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/
(2.)  https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/platform:2/addon-506646-latest.xpi
(3.)  https://addons.mozilla.org/firefox/downloads/file/1032365/

...which all seem to point to the same file, but I _feel_ like there should be a preferred URL to the latest version which isn't supposed to change. I'd say number one or two? 

Cheers

**Comment by mkaply** [comment]
This was a dumb mistake on my part.

I was trying to fix a problem with Firefox 63 and broke older builds.

I'll have a fix in a few minutes

**Comment by mkaply** [comment]
Fixed.

https://github.com/mkaply/cck2wizard/releases/tag/2.2.8

Sorry about that.

As far as preferred URL, I tend to use this:

https://addons.mozilla.org/firefox/downloads/file/1032365/privacy_badger-latest-an+fx.xpi

You get it by coping the URL for the download button, changing the version to "latest" and removing everything after th question mark.

That first URL seems good though too.

**Comment by bHKSG3kp** [comment]
Lovely, seems to be working, Thanks!
