### ISSUE TITLE
CCK 2.2.8 Certificates - Overrides

### ISSUE THREAD

**Issue by ffr-lco** [mkaply/cck2wizard#98]
I used Certificates-Overrides to add an exception for an internal website with an invalid certificate (unknown issuer and wrong servername).

While that worked fine with the old config created with CCK 2.2.3.2 for Firefox ESR 52.9 it does not work with CCK 2.2.8 and Firefox ESR 60.2.0. With the new version I still get the certificate error warning I tried to avoid by adding the exception.

**Comment by mkaply** [comment]
I have a fix for that I just did. It will be released later today,. If you want to grab it now, you can download this file

https://raw.githubusercontent.com/mkaply/cck2wizard/master/cck2/modules/CCK2.jsm

and replace it in your package.

**Comment by ffr-lco** [comment]
Thank you for the quick response, I can confirm the issue is fixed by that update :)
